#!/bin/sh

name="$1"
encoding="# -*- coding: utf-8 -*-"
vim="# vim: set syntax=yaml ts=2 sw=2 sts=2 et :"

if [ -z "$name" ]; then
  echo "Usage: $0 TEMPLATE_NAME" 2>&1
  exit 128
fi

mkdir -m 755 "$name"
cat <<EOF > $name/create.top
$encoding
$vim

base:
  dom0:
    - minimal.$name.create
EOF

cat <<EOF > $name/create.sls
$encoding
$vim

{%- from 'minimal/clonevm.sls' import maybe_clone_vm -%}
{%- from 'qvm/template.jinja' import load -%}

{% set config = pillar.get('$name-clone') %}

{{ maybe_clone_vm(config) -}}

{% load_yaml as defaults %}
name: $name
present:
  template: {{ config.name }}
{%- endload %}

{{ load(defaults) }}
EOF

cat <<EOF > $name/configure.top
$encoding
$vim

base:
  '': # replace with matching clause
    - minimal.$name.configure
EOF

cat <<EOF > $name/configure.sls
$encoding
$vim

# Init of configuration.
############################################################################################
EOF

printf "$name:\n  clone-config:\n    name: $name\n    source: #\n" >> /srv/pillar/base/minimal/init.sls

echo "INFO - Finished!"
